#pragma once
// screen display size
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 480

#define NUMBOXES 100
#define NUMPROJECTILES 100
#define NUMHEALTHPICKUPS 100
#define NUMAMMOPICKUPS 100

#define NUMPUNCHHITBOXES 100

#define NUMMELEEENEMIES 10
#define NUMRANGEDENEMIES 10

#define PLAYERMOVEMENTSPEED 150
